/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.exception.EmptyStringException;
import java.awt.event.ActionListener;
import java.util.EmptyStackException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Room;

/**
 *
 * @author Administrator
 */
public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    private Room room;

    public ClientView() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        roomForm.setLocationRelativeTo(this);
        roomForm.setResizable(false);
        
        room = new Room();
    }
    
    public void addActionListener(ActionListener actionListener) {
        
        roomSearch.addActionListener(actionListener);
        roomCreate.addActionListener(actionListener);
        roomDelete.addActionListener(actionListener);
        roomUpdate.addActionListener(actionListener);
        applyRoomBtn.addActionListener(actionListener);
        
    }
    
    public void addItems(List<Integer> floors){
        for(Integer i : floors){
            floorId.addItem(i);
        }
    }
    
    public Room getRoom() throws NumberFormatException, EmptyStringException {
        int floor = (int) floorId.getSelectedItem();
        
        if (roomArea.getText().equals("") || roomName.getText().equals("") || roomPopulation.getText().equals("")) {
            throw new EmptyStringException("Hãy nhập đủ các trường");
        }
        String name = roomName.getText();
        
        float area = Float.parseFloat(roomArea.getText().toString());
        
        int population = Integer.parseInt(roomPopulation.getText().toString());
        
        room.setName(name);
        room.setFloorId(floor);
        room.setArea(area);
        room.setPopulationOfRoom(population);
        room.setId(Integer.parseInt(roomId.getText().toString()));
        
        return room;
    }
    
    public int getRoomId() throws NumberFormatException, EmptyStringException{
        if(roomId.getText().equals(""))
            throw new EmptyStringException("Nhập trường ID!!!");
        
        int id = Integer.parseInt(roomId.getText().toString());
        
        return id;
    }
    
    public void setRoomForm(Room room){
        roomName.setText(room.getName());
        roomArea.setText(room.getArea()+"");
        roomPopulation.setText(room.getPopulationOfRoom()+"");
        floorId.setSelectedItem(room.getFloorId());
        floorId.setEnabled(false);
    }
    
    public void showRoomInfo(Room room){
        floorLb.setText("Floor : "+room.getFloorId());
        nameLb.setText("Name : "+room.getName());
        areaLb.setText("Area : "+room.getArea());
        populationLb.setText("Population : "+room.getPopulationOfRoom());
        
    }
    public void clearRoomInfo(){
        floorLb.setText("");
        nameLb.setText("");
        areaLb.setText("");
        populationLb.setText("");
        
    }
    
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public JButton getApplyRoomBtn() {
        return applyRoomBtn;
    }

   

    public JDialog getFloorForm() {
        return floorForm;
    }

    public JButton getRoomCreate() {
        return roomCreate;
    }

    public JButton getRoomDelete() {
        return roomDelete;
    }

    public JDialog getRoomForm() {
        return roomForm;
    }

    public JButton getRoomSearch() {
        return roomSearch;
    }

    public JButton getRoomUpdate() {
        return roomUpdate;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomForm = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        floorId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        roomName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roomArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roomPopulation = new javax.swing.JTextField();
        applyRoomBtn = new javax.swing.JButton();
        floorForm = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        floorName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        floorDecrip = new javax.swing.JTextField();
        addFloorbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        floorLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        areaLb = new javax.swing.JLabel();
        populationLb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roomId = new javax.swing.JTextField();
        roomSearch = new javax.swing.JButton();
        roomUpdate = new javax.swing.JButton();
        roomCreate = new javax.swing.JButton();
        roomDelete = new javax.swing.JButton();

        roomForm.setPreferredSize(new java.awt.Dimension(465, 400));
        roomForm.setResizable(false);
        roomForm.setSize(new java.awt.Dimension(480, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ROOM FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Floor");

        jLabel4.setText("Name");

        jLabel5.setText("Area");

        jLabel6.setText("Population");

        roomPopulation.setText("0");

        applyRoomBtn.setText("Apply");

        javax.swing.GroupLayout roomFormLayout = new javax.swing.GroupLayout(roomForm.getContentPane());
        roomForm.getContentPane().setLayout(roomFormLayout);
        roomFormLayout.setHorizontalGroup(
            roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomFormLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomFormLayout.createSequentialGroup()
                        .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(floorId, 0, 171, Short.MAX_VALUE)
                            .addComponent(roomName)
                            .addComponent(roomArea)
                            .addComponent(roomPopulation))))
                .addGap(110, 110, 110))
            .addGroup(roomFormLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(applyRoomBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomFormLayout.setVerticalGroup(
            roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(floorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roomArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(roomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roomPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(applyRoomBtn)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FLOOR FORM");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setText("Name");

        jLabel10.setText("Decription");

        addFloorbtn.setText("Add");

        javax.swing.GroupLayout floorFormLayout = new javax.swing.GroupLayout(floorForm.getContentPane());
        floorForm.getContentPane().setLayout(floorFormLayout);
        floorFormLayout.setHorizontalGroup(
            floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorFormLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(addFloorbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floorFormLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(floorFormLayout.createSequentialGroup()
                        .addGroup(floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(37, 37, 37)
                        .addGroup(floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floorName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floorDecrip, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        floorFormLayout.setVerticalGroup(
            floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(floorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(floorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(floorDecrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(addFloorbtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(floorLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(areaLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(populationLb, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(floorLb)
                .addGap(72, 72, 72)
                .addComponent(nameLb)
                .addGap(67, 67, 67)
                .addComponent(areaLb)
                .addGap(71, 71, 71)
                .addComponent(populationLb)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel1.setText("ID");

        roomSearch.setText("Search");

        roomUpdate.setText("Update");

        roomCreate.setText("Create");

        roomDelete.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(roomId)
                    .addComponent(roomSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(roomCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(roomId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(roomSearch)
                        .addGap(48, 48, 48)
                        .addComponent(roomUpdate)
                        .addGap(51, 51, 51)
                        .addComponent(roomDelete)
                        .addGap(46, 46, 46)
                        .addComponent(roomCreate))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Room", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFloorbtn;
    private javax.swing.JButton applyRoomBtn;
    private javax.swing.JLabel areaLb;
    private javax.swing.JTextField floorDecrip;
    private javax.swing.JDialog floorForm;
    private javax.swing.JComboBox<Integer> floorId;
    private javax.swing.JLabel floorLb;
    private javax.swing.JTextField floorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel populationLb;
    private javax.swing.JTextField roomArea;
    private javax.swing.JButton roomCreate;
    private javax.swing.JButton roomDelete;
    private javax.swing.JDialog roomForm;
    private javax.swing.JTextField roomId;
    private javax.swing.JTextField roomName;
    private javax.swing.JTextField roomPopulation;
    private javax.swing.JButton roomSearch;
    private javax.swing.JButton roomUpdate;
    // End of variables declaration//GEN-END:variables
}
